### ISSUE TITLE
为什么我换你的主题hexo generate报错呢 

### ISSUE THREAD

**Issue by cgq355716727** [yohnz/hexo-theme-card#1]
Unhandled rejection TypeError: G:\GitWorkSpace\blog\themes\card\layout\layout.ej
s:1

> > 1| <%- partial('common/head') %>
> >     2| <body>
> >     3|     <div id="container">
> >     4|         <%- partial('common/header') %>

G:\GitWorkSpace\blog\themes\card\layout\common\head.ejs:23
    21|     <title><% if (title) { %><%= title %> | <% } %><%= config.title %></
title>
    22|     <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1" />

> > 23|     <%- open_graph({
> >     24|         image:          thumbnail(page),
> >     25|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
> >     26|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:47:44)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:51:1075)
    at G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:1
22:20)
    at View.renderSync (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js
:50:21)
    at Object.partial (G:\GitWorkSpace\blog\node_modules\hexo\lib\plugins\helper
\partial.js:42:17)
    at Object.wrapper (G:\GitWorkSpace\blog\node_modules\lodash\lodash.js:4762:1
9)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:30:962)
    at G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:127:3
0)
    at View.render (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:29:
15)
    at G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (G:\GitWorkSpace\blog\node_modules\bluebird\js\release\util.js
:16:23)
    at Promise._settlePromiseFromHandler (G:\GitWorkSpace\blog\node_modules\blue
bird\js\release\promise.js:509:31)
    at Promise._settlePromise (G:\GitWorkSpace\blog\node_modules\bluebird\js\rel
ease\promise.js:566:18)
    at Promise._settlePromise0 (G:\GitWorkSpace\blog\node_modules\bluebird\js\re
lease\promise.js:611:10)
    at Promise._settlePromises (G:\GitWorkSpace\blog\node_modules\bluebird\js\re
lease\promise.js:690:18)
    at Async._drainQueue (G:\GitWorkSpace\blog\node_modules\bluebird\js\release\
async.js:138:16)
    at Async._drainQueues (G:\GitWorkSpace\blog\node_modules\bluebird\js\release
\async.js:148:10)
    at Immediate.Async.drainQueues (G:\GitWorkSpace\blog\node_modules\bluebird\j
s\release\async.js:17:14)
    at runCallback (timers.js:574:20)

Unhandled rejection TypeError: G:\GitWorkSpace\blog\themes\card\layout\layout.ej
s:1

> > 1| <%- partial('common/head') %>
> >     2| <body>
> >     3|     <div id="container">
> >     4|         <%- partial('common/header') %>

G:\GitWorkSpace\blog\themes\card\layout\common\head.ejs:23
    21|     <title><% if (title) { %><%= title %> | <% } %><%= config.title %></
title>
    22|     <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1" />

> > 23|     <%- open_graph({
> >     24|         image:          thumbnail(page),
> >     25|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
> >     26|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:47:44)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:51:1075)
    at G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:1
22:20)
    at View.renderSync (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js
:50:21)
    at Object.partial (G:\GitWorkSpace\blog\node_modules\hexo\lib\plugins\helper
\partial.js:42:17)
    at Object.wrapper (G:\GitWorkSpace\blog\node_modules\lodash\lodash.js:4762:1
9)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:30:962)
    at G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:127:3
0)
    at View.render (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:29:
15)
    at G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (G:\GitWorkSpace\blog\node_modules\bluebird\js\release\util.js
:16:23)
    at Promise._settlePromiseFromHandler (G:\GitWorkSpace\blog\node_modules\blue
bird\js\release\promise.js:509:31)
    at Promise._settlePromise (G:\GitWorkSpace\blog\node_modules\bluebird\js\rel
ease\promise.js:566:18)
    at Promise._settlePromise0 (G:\GitWorkSpace\blog\node_modules\bluebird\js\re
lease\promise.js:611:10)
    at Promise._settlePromises (G:\GitWorkSpace\blog\node_modules\bluebird\js\re
lease\promise.js:690:18)
    at Async._drainQueue (G:\GitWorkSpace\blog\node_modules\bluebird\js\release\
async.js:138:16)
    at Async._drainQueues (G:\GitWorkSpace\blog\node_modules\bluebird\js\release
\async.js:148:10)
    at Immediate.Async.drainQueues (G:\GitWorkSpace\blog\node_modules\bluebird\j
s\release\async.js:17:14)
    at runCallback (timers.js:574:20)

Unhandled rejection TypeError: G:\GitWorkSpace\blog\themes\card\layout\layout.ej
s:1

> > 1| <%- partial('common/head') %>
> >     2| <body>
> >     3|     <div id="container">
> >     4|         <%- partial('common/header') %>

G:\GitWorkSpace\blog\themes\card\layout\common\head.ejs:23
    21|     <title><% if (title) { %><%= title %> | <% } %><%= config.title %></
title>
    22|     <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1" />

> > 23|     <%- open_graph({
> >     24|         image:          thumbnail(page),
> >     25|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
> >     26|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:47:44)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:51:1075)
    at G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:1
22:20)
    at View.renderSync (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js
:50:21)
    at Object.partial (G:\GitWorkSpace\blog\node_modules\hexo\lib\plugins\helper
\partial.js:42:17)
    at Object.wrapper (G:\GitWorkSpace\blog\node_modules\lodash\lodash.js:4762:1
9)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:30:962)
    at G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:127:3
0)
    at View.render (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:29:
15)
    at G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (G:\GitWorkSpace\blog\node_modules\bluebird\js\release\util.js
:16:23)
    at Promise._settlePromiseFromHandler (G:\GitWorkSpace\blog\node_modules\blue
bird\js\release\promise.js:509:31)
    at Promise._settlePromise (G:\GitWorkSpace\blog\node_modules\bluebird\js\rel
ease\promise.js:566:18)
    at Promise._settlePromise0 (G:\GitWorkSpace\blog\node_modules\bluebird\js\re
lease\promise.js:611:10)
    at Promise._settlePromises (G:\GitWorkSpace\blog\node_modules\bluebird\js\re
lease\promise.js:690:18)
    at Async._drainQueue (G:\GitWorkSpace\blog\node_modules\bluebird\js\release\
async.js:138:16)
    at Async._drainQueues (G:\GitWorkSpace\blog\node_modules\bluebird\js\release
\async.js:148:10)
    at Immediate.Async.drainQueues (G:\GitWorkSpace\blog\node_modules\bluebird\j
s\release\async.js:17:14)
    at runCallback (timers.js:574:20)

Unhandled rejection TypeError: G:\GitWorkSpace\blog\themes\card\layout\layout.ej
s:1

> > 1| <%- partial('common/head') %>
> >     2| <body>
> >     3|     <div id="container">
> >     4|         <%- partial('common/header') %>

G:\GitWorkSpace\blog\themes\card\layout\common\head.ejs:23
    21|     <title><% if (title) { %><%= title %> | <% } %><%= config.title %></
title>
    22|     <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1" />

> > 23|     <%- open_graph({
> >     24|         image:          thumbnail(page),
> >     25|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
> >     26|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:47:44)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:51:1075)
    at G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:1
22:20)
    at View.renderSync (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js
:50:21)
    at Object.partial (G:\GitWorkSpace\blog\node_modules\hexo\lib\plugins\helper
\partial.js:42:17)
    at Object.wrapper (G:\GitWorkSpace\blog\node_modules\lodash\lodash.js:4762:1
9)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.
js:242:14), <anonymous>:30:962)
    at G:\GitWorkSpace\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:127:3
0)
    at View.render (G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:29:
15)
    at G:\GitWorkSpace\blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (G:\GitWorkSpace\blog\node_modules\bluebird\js\release\util.js
:16:23)
    at Promise._settlePromiseFromHandler (G:\GitWorkSpace\blog\node_modules\blue
bird\js\release\promise.js:509:31)
    at Promise._settlePromise (G:\GitWorkSpace\blog\node_modules\bluebird\js\rel
ease\promise.js:566:18)
    at Promise._settlePromise0 (G:\GitWorkSpace\blog\node_modules\bluebird\js\re
lease\promise.js:611:10)
    at Promise._settlePromises (G:\GitWorkSpace\blog\node_modules\bluebird\js\re
lease\promise.js:690:18)
    at Async._drainQueue (G:\GitWorkSpace\blog\node_modules\bluebird\js\release\
async.js:138:16)
    at Async._drainQueues (G:\GitWorkSpace\blog\node_modules\bluebird\js\release
\async.js:148:10)
    at Immediate.Async.drainQueues (G:\GitWorkSpace\blog\node_modules\bluebird\j
s\release\async.js:17:14)
    at runCallback (timers.js:574:20)

ERROR Asset render failed: css/style.css
CoercionError: G:/GitWorkSpace/blog/themes/card/source/css/_variables.styl:28:54

   24| // Header
   25| header-height = 64px
   26| header-sub-height = 48px
   27| logo-url = hexo-config("customize.logo.url")
   28| logo-width = 0px + hexo-config("customize.logo.width")
------------------------------------------------------------^
   29| logo-height = 0px + hexo-config("customize.logo.height")
   30|
   31| // Sidebar

cannot coerce '' to unit

```
at Unit.Node.coerce (G:\GitWorkSpace\blog\node_modules\stylus\lib\nodes\node
```

.js:248:11)
    at Unit.coerce (G:\GitWorkSpace\blog\node_modules\stylus\lib\nodes\unit.js:2
09:43)
    at Unit.operate (G:\GitWorkSpace\blog\node_modules\stylus\lib\nodes\unit.js:
132:20)
    at Evaluator.visitBinOp (G:\GitWorkSpace\blog\node_modules\stylus\lib\visito
r\evaluator.js:567:28)
    at Evaluator.Visitor.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\vis
itor\index.js:28:40)
    at Evaluator.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\visitor\eva
luator.js:156:18)
    at Evaluator.visitExpression (G:\GitWorkSpace\blog\node_modules\stylus\lib\v
isitor\evaluator.js:630:26)
    at Evaluator.Visitor.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\vis
itor\index.js:28:40)
    at Evaluator.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\visitor\eva
luator.js:156:18)
    at Evaluator.visitIdent (G:\GitWorkSpace\blog\node_modules\stylus\lib\visito
r\evaluator.js:537:22)
    at Evaluator.Visitor.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\vis
itor\index.js:28:40)
    at Evaluator.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\visitor\eva
luator.js:156:18)
    at Evaluator.visitBlock (G:\GitWorkSpace\blog\node_modules\stylus\lib\visito
r\evaluator.js:706:39)
    at Evaluator.Visitor.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\vis
itor\index.js:28:40)
    at Evaluator.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\visitor\eva
luator.js:156:18)
    at Evaluator.importFile (G:\GitWorkSpace\blog\node_modules\stylus\lib\visito
r\evaluator.js:95:18)
    at Evaluator.visitImport (G:\GitWorkSpace\blog\node_modules\stylus\lib\visit
or\evaluator.js:906:27)
    at Evaluator.Visitor.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\vis
itor\index.js:28:40)
    at Evaluator.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\visitor\eva
luator.js:156:18)
    at Evaluator.visitRoot (G:\GitWorkSpace\blog\node_modules\stylus\lib\visitor
\evaluator.js:693:27)
    at Evaluator.Visitor.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\vis
itor\index.js:28:40)
    at Evaluator.visit (G:\GitWorkSpace\blog\node_modules\stylus\lib\visitor\eva
luator.js:156:18)
INFO  Generated: css/images/avatar1.png
INFO  Generated: css/images/avatar.jpg
INFO  Generated: css/images/hexo-theme-card.png

**Comment by yohnz** [comment]
@cgq355716727  `git pull`一下

**Comment by cgq355716727** [comment]
我都没上传 在本地构建

**Comment by yohnz** [comment]
@cgq355716727 我是说重新pull一下主题，我有修复上面的问题

**Comment by cgq355716727** [comment]
哦好的谢谢

**Comment by yohnz** [comment]
@cgq355716727 客气了
